
import "./globals.css";
import { UserProvider } from "@/redux/userContext";
import Pageload from "@/components/pageload";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import "@/public/fonts/Circularstd/stylesheet.css";
import "@/public/fonts/Helvatica/stylesheet.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

    <body >
    <Suspense fallback={<Pageload/>}>

       <UserProvider>


      {children}
      </UserProvider>
      <Toaster />

      </Suspense>
      </body>
  </html>
  );
}
